// <auto-generated />
using System;
using FoundU.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoundU.Infrastructure.Migrations
{
    [DbContext(typeof(FoundUDbContext))]
    partial class FoundUDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoundU.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FinalOutcomeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TriggerEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("Status");

                    b.HasIndex("TriggerEntityType", "TriggerEntityId");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId", "StepOrder")
                        .IsUnique();

                    b.ToTable("AgentSteps", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("SuspendedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("IsSuspended");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_StudentNumber_Unique")
                        .HasFilter("\"StudentNumber\" IS NOT NULL");

                    b.HasIndex("SuspendedByUserId");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OverriddenByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("IsOverride");

                    b.HasIndex("OverriddenByUserId");

                    b.ToTable("ApprovalDecisions", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.CampusLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Building")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Building")
                        .IsUnique();

                    b.ToTable("CampusLocations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            Building = "Building C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Library",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111112"),
                            Building = "Building B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lecture Hall B12",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111113"),
                            Building = "Building A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cafeteria",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111114"),
                            Building = "Sports Block",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sports Complex",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111115"),
                            Building = "Building A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Main Auditorium",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111116"),
                            Building = "Building A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Security Desk",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111117"),
                            Building = "Outdoor",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parking Lot",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phones, laptops, chargers, headphones",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Backpacks, handbags, wallets, purses",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bags & Wallets",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jackets, hats, scarves and other apparel",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Clothing",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Student IDs, cards, documents",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Documents & Cards",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "House, locker, or vehicle keys",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Keys",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111116"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Watches, jewelry, glasses",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Jewelry & Accessories",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111117"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Textbooks, notebooks, stationery",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Books & Stationery",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111118"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anything not covered above",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Other",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LostReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId")
                        .IsUnique()
                        .HasDatabaseName("IX_Claims_FoundReportId_OneApproved")
                        .HasFilter("\"Status\" = 'Approved'");

                    b.HasIndex("LostReportId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ClaimAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("VerificationQuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("VerificationQuestionId")
                        .IsUnique();

                    b.ToTable("ClaimAnswers", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ClaimStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimStatusHistories", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundItemPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId");

                    b.ToTable("FoundItemPhotos", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FoundLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservedAttributesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrivateVerificationAttributesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PrivateVerificationDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FoundAt");

                    b.HasIndex("FoundLocationId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("StaffId");

                    b.HasIndex("Status");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("Status", "CategoryId", "ItemTypeId", "FoundLocationId");

                    b.ToTable("FoundReports", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundReportStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("FoundReportId");

                    b.ToTable("FoundReportStatusHistories", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("ItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Laptop",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111112"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Phone",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111113"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Headphones",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111114"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Earphones",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111115"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Backpack",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111116"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Laptop Bag",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111117"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Purse",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111118"),
                            CategoryId = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Wallet",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostItemPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LostReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LostReportId");

                    b.ToTable("LostItemPhotos", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EstimatedLostFromAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("EstimatedLostToAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("IdentifyingFeaturesJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastSeenLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParsedAttributesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("WithdrawReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("LastSeenLocationId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("EstimatedLostFromAt", "EstimatedLostToAt");

                    b.HasIndex("Status", "CategoryId", "ItemTypeId", "LastSeenLocationId");

                    b.ToTable("LostReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_LostReports_EstimatedLostRange", "\"EstimatedLostFromAt\" <= \"EstimatedLostToAt\"");
                        });
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostReportStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LostReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("LostReportId");

                    b.ToTable("LostReportStatusHistories", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.MatchStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("MatchSuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("MatchSuggestionId");

                    b.ToTable("MatchStatusHistories", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.MatchSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictingFactorsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GeneratedByAgentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LostReportId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("MatchingFactorsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId");

                    b.HasIndex("GeneratedByAgentRunId");

                    b.HasIndex("MatchScore");

                    b.HasIndex("Status");

                    b.HasIndex("LostReportId", "FoundReportId")
                        .IsUnique();

                    b.ToTable("MatchSuggestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchSuggestions_MatchScore_Range", "\"MatchScore\" >= 0 AND \"MatchScore\" <= 1");
                        });
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Building")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StorageLocations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            Building = "Building A",
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Security Desk - Building A",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FoundU.Domain.Entities.StorageTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromStorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ToStorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("TransferredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId");

                    b.HasIndex("FromStorageLocationId");

                    b.HasIndex("ToStorageLocationId");

                    b.HasIndex("TransferredAt");

                    b.HasIndex("TransferredByUserId");

                    b.ToTable("StorageTransfers", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.VerificationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("GeneratedByAgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("GeneratedByAgentRunId");

                    b.ToTable("VerificationQuestions", (string)null);
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AgentRun", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Claim", "Claim")
                        .WithMany("AgentRuns")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AgentStep", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("Steps")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "SuspendedByUser")
                        .WithMany()
                        .HasForeignKey("SuspendedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SuspendedByUser");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Claim", "Claim")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AppUser", "DecidedByUser")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AppUser", "OverriddenByUser")
                        .WithMany()
                        .HasForeignKey("OverriddenByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("DecidedByUser");

                    b.Navigation("OverriddenByUser");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Claim", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.FoundReport", "FoundReport")
                        .WithMany("Claims")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.LostReport", "LostReport")
                        .WithMany("Claims")
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AppUser", "Student")
                        .WithMany("Claims")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoundReport");

                    b.Navigation("LostReport");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ClaimAnswer", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Claim", "Claim")
                        .WithMany("Answers")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.VerificationQuestion", "VerificationQuestion")
                        .WithOne("Answer")
                        .HasForeignKey("FoundU.Domain.Entities.ClaimAnswer", "VerificationQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("VerificationQuestion");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ClaimStatusHistory", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoundU.Domain.Entities.Claim", "Claim")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundItemPhoto", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.FoundReport", "FoundReport")
                        .WithMany("Photos")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoundReport");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundReport", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Category", "Category")
                        .WithMany("FoundReports")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.CampusLocation", "FoundLocation")
                        .WithMany("FoundReportsFoundHere")
                        .HasForeignKey("FoundLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.ItemType", "ItemType")
                        .WithMany("FoundReports")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AppUser", "Staff")
                        .WithMany("FoundReports")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.StorageLocation", "StorageLocation")
                        .WithMany("FoundReports")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FoundLocation");

                    b.Navigation("ItemType");

                    b.Navigation("Staff");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundReportStatusHistory", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoundU.Domain.Entities.FoundReport", "FoundReport")
                        .WithMany("StatusHistory")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("FoundReport");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ItemType", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Category", "Category")
                        .WithMany("ItemTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostItemPhoto", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.LostReport", "LostReport")
                        .WithMany("Photos")
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LostReport");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostReport", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Category", "Category")
                        .WithMany("LostReports")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.ItemType", "ItemType")
                        .WithMany("LostReports")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.CampusLocation", "LastSeenLocation")
                        .WithMany("LostReportsLastSeenHere")
                        .HasForeignKey("LastSeenLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AppUser", "Student")
                        .WithMany("LostReports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ItemType");

                    b.Navigation("LastSeenLocation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostReportStatusHistory", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoundU.Domain.Entities.LostReport", "LostReport")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("LostReport");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.MatchStatusHistory", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoundU.Domain.Entities.MatchSuggestion", "MatchSuggestion")
                        .WithMany("StatusHistory")
                        .HasForeignKey("MatchSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("MatchSuggestion");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.MatchSuggestion", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.FoundReport", "FoundReport")
                        .WithMany("MatchSuggestions")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AgentRun", "GeneratedByAgentRun")
                        .WithMany("MatchSuggestions")
                        .HasForeignKey("GeneratedByAgentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoundU.Domain.Entities.LostReport", "LostReport")
                        .WithMany("MatchSuggestions")
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoundReport");

                    b.Navigation("GeneratedByAgentRun");

                    b.Navigation("LostReport");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.StorageTransfer", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.FoundReport", "FoundReport")
                        .WithMany("StorageTransfers")
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.StorageLocation", "FromStorageLocation")
                        .WithMany("TransfersFrom")
                        .HasForeignKey("FromStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoundU.Domain.Entities.StorageLocation", "ToStorageLocation")
                        .WithMany("TransfersTo")
                        .HasForeignKey("ToStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AppUser", "TransferredByUser")
                        .WithMany("StorageTransfers")
                        .HasForeignKey("TransferredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoundReport");

                    b.Navigation("FromStorageLocation");

                    b.Navigation("ToStorageLocation");

                    b.Navigation("TransferredByUser");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.VerificationQuestion", b =>
                {
                    b.HasOne("FoundU.Domain.Entities.Claim", "Claim")
                        .WithMany("VerificationQuestions")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundU.Domain.Entities.AgentRun", "GeneratedByAgentRun")
                        .WithMany("VerificationQuestions")
                        .HasForeignKey("GeneratedByAgentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Claim");

                    b.Navigation("GeneratedByAgentRun");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AgentRun", b =>
                {
                    b.Navigation("MatchSuggestions");

                    b.Navigation("Steps");

                    b.Navigation("VerificationQuestions");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("AuditLogs");

                    b.Navigation("Claims");

                    b.Navigation("FoundReports");

                    b.Navigation("LostReports");

                    b.Navigation("Notifications");

                    b.Navigation("StorageTransfers");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.CampusLocation", b =>
                {
                    b.Navigation("FoundReportsFoundHere");

                    b.Navigation("LostReportsLastSeenHere");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Category", b =>
                {
                    b.Navigation("FoundReports");

                    b.Navigation("ItemTypes");

                    b.Navigation("LostReports");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.Claim", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("Answers");

                    b.Navigation("ApprovalDecisions");

                    b.Navigation("StatusHistory");

                    b.Navigation("VerificationQuestions");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.FoundReport", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("MatchSuggestions");

                    b.Navigation("Photos");

                    b.Navigation("StatusHistory");

                    b.Navigation("StorageTransfers");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.ItemType", b =>
                {
                    b.Navigation("FoundReports");

                    b.Navigation("LostReports");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.LostReport", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("MatchSuggestions");

                    b.Navigation("Photos");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.MatchSuggestion", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.StorageLocation", b =>
                {
                    b.Navigation("FoundReports");

                    b.Navigation("TransfersFrom");

                    b.Navigation("TransfersTo");
                });

            modelBuilder.Entity("FoundU.Domain.Entities.VerificationQuestion", b =>
                {
                    b.Navigation("Answer");
                });
#pragma warning restore 612, 618
        }
    }
}
