using FoundU.Domain.Common;

namespace FoundU.Domain.Entities;

/// <summary>
/// A question generated by the Verification Agent from FoundReport.PrivateVerificationDetails,
/// without revealing the answer itself.
/// </summary>
public class VerificationQuestion : BaseEntity
{
    public Guid ClaimId { get; set; }
    public Claim Claim { get; set; } = default!;

    public string QuestionText { get; set; } = default!;

    public Guid? GeneratedByAgentRunId { get; set; }
    public AgentRun? GeneratedByAgentRun { get; set; }

    public ClaimAnswer? Answer { get; set; }
}
